language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1//0f28YJhe4_p-ICgYIARAAGA8SNwF-L9IrbvQE-dGbWRyDKpT_8qnfV6mX4raM4tlVBGhD-TKAOXJh2GCpVR5xd_WCYDluDwJ6kA4"